providers = ["node"]

# Le decimos explícitamente a Nixpacks que use Node 20
[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build -- --configuration=production"]